#### 1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 

In [2]:
np.__version__

'1.23.4'

In [3]:
np.show_config()

openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFI

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
ar = np.zeros(10)
ar

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 


In [5]:
print("The Memory size of an array is: ", np.size(ar))

The Memory size of an array is:  10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [7]:
ea = np.zeros(10)
ea[4]=1
ea

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
r = np.arange(10,50)
r

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆) 

In [9]:
r[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
a = np.arange(0,9).reshape(3, -1)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
b = [1,2,0,0,4,0]
b1 = np.array(b)
b1.nonzero()

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random((3,3,3))

array([[[0.89195437, 0.20917165, 0.59744149],
        [0.06002463, 0.66428646, 0.39669565],
        [0.92846526, 0.34679372, 0.87739398]],

       [[0.45194514, 0.57423081, 0.41769592],
        [0.85757348, 0.70289086, 0.37008565],
        [0.53914419, 0.8066801 , 0.37508163]],

       [[0.43257186, 0.58376338, 0.93877846],
        [0.4364937 , 0.94522357, 0.23000168],
        [0.48936112, 0.06356034, 0.56528687]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 

In [14]:
s = np.random.random((10,10))

In [15]:
s

array([[0.25573255, 0.46611167, 0.73652948, 0.66467184, 0.07057975,
        0.2449068 , 0.76359224, 0.44877056, 0.97596585, 0.59327464],
       [0.8308808 , 0.77822533, 0.8824416 , 0.8065411 , 0.29553811,
        0.47634482, 0.04528919, 0.53765024, 0.40723011, 0.06918034],
       [0.87740408, 0.27108159, 0.48455721, 0.96098277, 0.60386103,
        0.53180927, 0.20830887, 0.79471805, 0.72956076, 0.97223489],
       [0.9544708 , 0.5369504 , 0.14722517, 0.10288276, 0.08324514,
        0.38816872, 0.04096264, 0.89962095, 0.85196643, 0.2644862 ],
       [0.18701004, 0.14127203, 0.05493408, 0.23475439, 0.84409689,
        0.4837694 , 0.54840491, 0.47737412, 0.98052631, 0.97806232],
       [0.57429072, 0.67309657, 0.25147663, 0.24750043, 0.54893363,
        0.76404628, 0.36129188, 0.90825433, 0.93139538, 0.09010396],
       [0.44884244, 0.7650821 , 0.56583677, 0.91575193, 0.87871672,
        0.42160451, 0.91770038, 0.52854929, 0.7026348 , 0.90946299],
       [0.40011635, 0.08516693, 0.3447516

In [16]:
s.min()

0.019476578452569226

In [17]:
s.max()

0.9861583453086514

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
t = np.random.random(30)

In [19]:
t.mean()

0.47890122270581437

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 

In [20]:
z = np.ones((5,5), dtype=int)
z[1:-1, 1:-1]=0
z

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 

In [21]:
np.pad(z, 1)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

In [22]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [23]:
p = np.arange(1,5)
w = np.diag(p, k=-1)
w

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [24]:
x = np.zeros((8,8), dtype=int)
x[1::2, ::2]=1
x[::2, 1::2]=1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [25]:
d = np.unravel_index(100, (6,7,8), order="C")
d

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [26]:
a= np.array([[0,1],[1,0]])
np.tile(a, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [27]:
s = np.arange(25).reshape(5,5)
ma, mi = s.max(), s.min()
s = (s-mi)/(ma-mi)
s

array([[0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667],
       [0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ],
       [0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333],
       [0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667],
       [0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
a = np.arange(15).reshape(5,-1)
b = np.arange(11,17).reshape(3,-1)
dt = np.dot(a, b)
dt

array([[ 43,  46],
       [160, 172],
       [277, 298],
       [394, 424],
       [511, 550]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 

In [29]:
A1 = np.arange(20)
A1[(A1>3) & (A1<=8)]*=-1
A1

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆)

In [30]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆) 

Z**Z

2 << Z >> 2

Z <- Z

1j*Z

Z/1/1

Z<Z>Z

Nothing

#### 28. What are the result of the following expressions?

In [31]:
np.array(0) / np.array(0)

C:\Users\Revanth\AppData\Local\Temp\ipykernel_22132\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [32]:
np.array(0) // np.array(0)

C:\Users\Revanth\AppData\Local\Temp\ipykernel_22132\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [33]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [34]:
d = np.random.uniform(-15, 5, 5)
d

array([ 2.19620858, -8.73801579, -3.27383188, -2.03443959, -9.41797007])

In [35]:
np.copysign(np.ceil(np.abs(d)), d)

array([  3.,  -9.,  -4.,  -3., -10.])

#### 30. How to find common values between two arrays? (★☆☆)

In [36]:
a = np.array([1,2,4])
b = np.array([2,5,7])
np.intersect1d(a,b)

array([2])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [37]:
np.seterr(all="ignore")
np.array(0) / np.array(0)

nan

#### 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

##### False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [38]:
Yesterday = np.datetime64("today", "D") - np.timedelta64(1, "D")
print(Yesterday)
Today = np.datetime64("today", "D")
print(Today)
Tomorrow = np.datetime64("today", "D") + np.timedelta64(1, "D")
print(Tomorrow)

2022-11-29
2022-11-30
2022-12-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [39]:
np.arange("2016-07-01", "2016-08-01", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [40]:
A = np.array([5,2,3,4]).astype("float64")
B = np.array([5,6,7,8]).astype("float64")
np.add(A,B, out=B)
np,divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)

array([-25.,  -8., -15., -24.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [41]:
a=np.random.uniform(2, 10, 10)
m1 = np.ceil(a)-1
print(m1)
m2 = np.trunc(a)
print(m2)
m3 = np.floor(a)
print(m3)
m4 = a.astype("int64")
print(m4)
m5 = a-a%1
print(m5)

[9. 3. 4. 5. 6. 5. 3. 3. 2. 2.]
[9. 3. 4. 5. 6. 5. 3. 3. 2. 2.]
[9. 3. 4. 5. 6. 5. 3. 3. 2. 2.]
[9 3 4 5 6 5 3 3 2 2]
[9. 3. 4. 5. 6. 5. 3. 3. 2. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 

In [42]:
s = np.zeros(25).reshape(5,5)
s=s+arange(5)
s

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [43]:
def gen():
    for c in range(10):
        i = c+c
        yield i
ar = np.fromiter(gen(), dtype="float64")
ar

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [44]:
v = np.linspace(0, 1, num=11, endpoint=False)
v[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 

In [45]:
r = np.random.random(10)
r.sort()
r

array([0.18920806, 0.24456894, 0.24486451, 0.35450909, 0.44461139,
       0.58726857, 0.61639883, 0.81924874, 0.85963766, 0.90539202])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [46]:
arr = [1,5,8]
np.add.reduce(arr)

14

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [47]:
a1 = np.random.uniform(2,6,5)
a2 = np.random.uniform(2,6,5)
print(a1)
print(a2)
print(np.array_equal(a1, a2))
print(np.allclose(a1,a2))

[5.41103398 4.26291124 5.13843762 2.33835073 4.63790755]
[5.75936925 5.44664346 4.14549163 2.86142491 3.06355075]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [48]:
m = np.random.random(10)
m.flags.writeable=False
m[4]=5

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [49]:
M = np.random.random((10,2))
print(M)
a, b = M[:,0], M[:,1]
c = np.sqrt(a**2+b**2)
d = np.arctan2(b,a)
print(c)
print(d)

[[0.42868958 0.48979011]
 [0.57786435 0.49121367]
 [0.47443144 0.04746895]
 [0.99963963 0.07027269]
 [0.25690647 0.38544182]
 [0.15079424 0.03095416]
 [0.79365928 0.95967307]
 [0.87817687 0.48108146]
 [0.27216197 0.67507328]
 [0.72339263 0.7342605 ]]
[0.65089869 0.75843133 0.47680026 1.0021066  0.46321305 0.1539385
 1.24533829 1.00131613 0.72787091 1.03074506]
[0.85182385 0.70452318 0.09972251 0.07018257 0.98289206 0.2024617
 0.87980144 0.50116675 1.18756952 0.79285375]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [50]:
A = np.random.random(10)
print(A)
A[np.argmax(A)]=0
print(A)

[0.91112364 0.4946053  0.33662908 0.38811161 0.35544509 0.74126219
 0.12484439 0.93226226 0.5862236  0.18995812]
[0.91112364 0.4946053  0.33662908 0.38811161 0.35544509 0.74126219
 0.12484439 0.         0.5862236  0.18995812]


#### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [51]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))


In [52]:
X = np.arange(8)
Y= X+0.5
Y

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [53]:
for i in [np.int8, np.int32, np.int64]:
    print(np.iinfo(i))
for f in [np.float32, np.float64]:
    print("Maximum value of ",f,"is ",np.finfo(f).max)
    print("Minimum value of ",f,"is ",np.finfo(f).min)

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Maximum value of  <class 'numpy.float32'> is  3.4028235e+38
Minimum value of  <class 'numpy.float32'> is  -3.4028235e+38
Maximum value of  <class 'numpy.float64'> is  1.7976931348623157e+308
Minimum value of  <class 'numpy.float64'> is  -1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [54]:
A = np.ones((20,20))
np.set_printoptions(threshold=None)
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [55]:
W = np.arange(100)
X = np.random.uniform(0,100)
print("Random Scalar value is",X)
ind = (np.abs(W-X)).argmin()
print("Closest Value is ",W[ind])

Random Scalar value is 61.855806000478744
Closest Value is  62


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 

In [56]:
R = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
                   ('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
R


C:\Users\Revanth\AppData\Local\Temp\ipykernel_22132\1168596840.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  R = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [57]:
F = np.random.random((100,2))
A,B = np.atleast_2d(F[:,0], F[:,1])
ans = np.sqrt((A-A.T)**2 + (B-B.T)**2)
print(ans)

[[0.         0.33282321 0.45857612 ... 0.40629981 0.21273065 0.7111179 ]
 [0.33282321 0.         0.50553562 ... 0.25068264 0.54163932 0.88536739]
 [0.45857612 0.50553562 0.         ... 0.2968704  0.58525225 0.4118679 ]
 ...
 [0.40629981 0.25068264 0.2968704  ... 0.         0.60688454 0.70617657]
 [0.21273065 0.54163932 0.58525225 ... 0.60688454 0.         0.71833987]
 [0.7111179  0.88536739 0.4118679  ... 0.70617657 0.71833987 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 

In [58]:
A = np.arange(15).astype("float32")
A = A.astype("int32", copy=False)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 54. How to read the following file? (★★☆)
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

In [59]:
from io import StringIO
S = StringIO("""1, 2, 3, 4, 5\n 6, , , 7, 8\n , , 9,10,11""")
D = np.genfromtxt(S, delimiter=",")
D

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [60]:
S = np.arange(12).reshape(4,3)
for val in np.ndenumerate(S):
    print(val)

((0, 0), 0)
((0, 1), 1)
((0, 2), 2)
((1, 0), 3)
((1, 1), 4)
((1, 2), 5)
((2, 0), 6)
((2, 1), 7)
((2, 2), 8)
((3, 0), 9)
((3, 1), 10)
((3, 2), 11)


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [61]:
A,B = np.meshgrid(np.linspace(-10,1,10), np.linspace(-10,1,10))
C = np.sqrt(A*A+B*B)
sigma, mu = 1.0, 0.0
Gau = np.exp(-( (C-mu)**2 / ( 2.0 * sigma**2 ) ) )
Gau

array([[3.72007598e-44, 3.58273784e-39, 7.74671109e-35, 3.76061432e-31,
        4.09863589e-28, 1.00290314e-25, 5.50957053e-24, 6.79540917e-23,
        1.88170953e-22, 1.16984592e-22],
       [3.58273784e-39, 3.45046997e-34, 7.46071725e-30, 3.62177959e-26,
        3.94732205e-23, 9.65877859e-21, 5.30616766e-19, 6.54453558e-18,
        1.81224039e-17, 1.12665743e-17],
       [7.74671109e-35, 7.46071725e-30, 1.61318030e-25, 7.83112841e-22,
        8.53502679e-19, 2.08845220e-16, 1.14731665e-14, 1.41508055e-13,
        3.91848451e-13, 2.43609496e-13],
       [3.76061432e-31, 3.62177959e-26, 7.83112841e-22, 3.80159442e-18,
        4.14329947e-15, 1.01383195e-12, 5.56960932e-11, 6.86945998e-10,
        1.90221486e-09, 1.18259394e-09],
       [4.09863589e-28, 3.94732205e-23, 8.53502679e-19, 4.14329947e-15,
        4.51571857e-12, 1.10495990e-09, 6.07023181e-08, 7.48691911e-07,
        2.07319481e-06, 1.28889101e-06],
       [1.00290314e-25, 9.65877859e-21, 2.08845220e-16, 1.01383195e-12,
   

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [62]:
S = np.ones((7,7), dtype="int32")
np.put(S,np.random.choice(range(7*7), 5, replace=False), 99)
S

array([[ 1,  1, 99,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1, 99,  1],
       [ 1,  1,  1, 99,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1],
       [ 1,  1, 99,  1,  1,  1,  1],
       [99,  1,  1,  1,  1,  1,  1]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [63]:
X = np.arange(16).reshape(4,4)
X= X-X.mean(axis=1)
X

array([[ -1.5,  -4.5,  -7.5, -10.5],
       [  2.5,  -0.5,  -3.5,  -6.5],
       [  6.5,   3.5,   0.5,  -2.5],
       [ 10.5,   7.5,   4.5,   1.5]])

#### 59. How to sort an array by the nth column? (★★☆)

In [64]:
Y = np.arange(16,0,-1).reshape(4,4)
Y[Y[:,1].argsort()]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [65]:
f = np.arange(20).reshape(5,4)
print((~f.any(axis=0).any()))

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [66]:
W = np.arange(100)
X = np.random.uniform(0,100)
print("Random Scalar value is",X)
ind = (np.abs(W-X)).argmin()
print("Closest Value is ",W[ind])

Random Scalar value is 12.286054584202933
Closest Value is  12


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [67]:
Q = np.arange(3).reshape(1,3)
R = np.arange(3).reshape(3,1)
ite = np.nditer([Q,R,None])
for a,b,c in ite: 
    c[...]=a+b
print(ite.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [68]:
class Name(np.ndarray):
    def __new__(cls, array, name="no name"):
        A = np.asarray(array).view(cls)
        A.name = name
        return A
    def __array_finalize__(self, A):
        if A is None: return
        self.info = getattr(A, 'name', "no name")

C = Name(np.arange(10), "range_10")
print (C.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [69]:
O = np.ones(10)
E = np.random.randint(0,len(O),20)
#O+=np.bincount(E,minlength=len(O))
np.add.at(O,E,1)
print(O)

[6. 3. 3. 4. 3. 3. 2. 2. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [70]:
R=[2,5,3,5,7,2,9]
E=[1,5,2,6,7,1,5]
V=np.bincount(E,R)
V

array([ 0.,  4.,  3.,  0.,  0., 14.,  5.,  7.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [71]:
w,h = 20,20
R = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
E = R[...,0]*(256*256) + R[...,1]*256 +R[...,2]
V = len(np.unique(E))
print(V)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [72]:
q = np.random.randint(0,10,(3,3,3,3))
Sum= q.sum(axis=(-2,-1))
Sum

array([[40, 50, 34],
       [28, 44, 45],
       [34, 27, 41]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

In [73]:
a = np.random.uniform(0,1,100)
b = np.random.randint(0,10,100)
Sum = np.bincount(b, weights=a)
Count = np.bincount(b)
mean = Sum / Count
print(mean)


[0.34250932 0.36682665 0.33029992 0.59301608 0.48805886 0.62215759
 0.40490632 0.47310807 0.50395661 0.53247172]


#### 69. How to get the diagonal of a dot product? (★★★)

In [74]:
a = np.arange(9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
dia = np.diag(np.dot(a,b))
dia

array([ 45, 174, 321])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [75]:
s = np.array([1,2,3,4,5])
n = 3
st = np.zeros(len(s) + (len(s)-1)*n)
st[::n+1] = s
print(st)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [76]:
w = np.ones((5,5,3))
x = 3*np.ones((5,5))
print(w * x[:,:,None])

[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


#### 72. How to swap two rows of an array? (★★★)

In [77]:
p = np.arange(25).reshape(5,5)
p[[0,1]] = p[[1,0]]
print(p)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

In [78]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
G

array([( 3, 73), ( 3, 81), (14, 24), (14, 90), (16, 52), (16, 60),
       (21, 53), (21, 66), (22, 40), (22, 55), (24, 33), (24, 90),
       (24, 91), (26, 70), (26, 76), (33, 91), (35, 94), (35, 95),
       (38, 66), (38, 81), (40, 55), (52, 60), (52, 77), (52, 82),
       (53, 66), (66, 81), (70, 76), (73, 81), (77, 82), (94, 95)],
      dtype=[('p0', '<i4'), ('p1', '<i4')])

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [79]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [80]:
N = np.random.randint(0,2,100)
np.logical_not(N, out=N)

N = np.random.uniform(-2.0,2.0,100)
np.negative(N, out=N)


array([ 0.6920018 ,  0.66019544, -0.90785059,  0.91689417, -0.12089676,
        1.94255339,  0.98879991,  1.35907674,  0.44259721,  1.75806133,
       -0.68819124, -0.34689655,  1.64255665,  1.58613672,  0.99940913,
        0.90584352, -1.18638337,  1.14941194, -1.75165447,  1.79482056,
        0.44568786, -0.0502694 , -0.78570393,  1.0853235 , -1.29706908,
        0.24817037, -1.03028863,  0.2096781 ,  1.49099571, -0.33633019,
        1.80180595,  0.50487993, -1.7386103 , -0.67455284, -1.61946525,
        0.44244556,  1.54403181,  0.06999119,  0.85134603, -1.97430224,
        1.69577578,  1.75252242, -0.18873909,  1.15668268, -0.81475091,
       -0.46712277,  1.29555991, -0.19757283, -0.61365199,  1.90061386,
       -1.34443878,  1.46806659,  1.97323736, -0.34960424,  0.8016245 ,
        1.2921993 , -0.19695306,  1.165876  ,  0.0822835 ,  1.70193571,
        0.72458324, -0.12875949, -0.97829818, -1.5371144 , -0.14872459,
        0.63254989, -1.32807589,  1.72943228, -1.61869928, -1.52

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [81]:
A = np.random.uniform(0,1,(13,15))
x, y, z = np.linalg.svd(A) 
rank = np.sum(y > 1e-10)
print(rank)

13


#### 83. How to find the most frequent value in an array?

In [82]:
A = np.random.randint(0,30,75)
print(np.bincount(A).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [83]:
w, x = 10, 20
q = np.ones((w,x,x))
r = np.ones((w,x,1))
s = np.tensordot(q, r, axes=[[0, 2], [0, 1]])
print(s)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)¶

In [84]:
q = np.ones((16,16))
r = 4
s = np.add.reduceat(np.add.reduceat(q, np.arange(0, q.shape[0], r), axis=0),
                                       np.arange(0, q.shape[1], r), axis=1)
print(s)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [85]:
A = np.arange(10000)
np.random.shuffle(A)
n = 5
print (A[np.argsort(A)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [86]:
A = np.array([("Raj", 5.5, 1),
              ("Ramesh", 3.9, 2)])
B = np.core.records.fromarrays(A.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(B)

[(b'Raj', 5.5, 1) (b'Ramesh', 3.9, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [87]:
x = np.random.rand(57)
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.52 µs ± 505 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.65 µs ± 338 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
4.14 µs ± 386 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [88]:
s = np.random.randint(0,10,(8,3))
t = np.random.randint(0,10,(2,2))

A = (s[..., np.newaxis, np.newaxis] == t)
rows = np.where(A.any((3,1)).all(1))[0]
print(rows)


[0 3]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)¶


In [89]:
R= np.random.randint(0,5,(10,3))
print(R)
E = np.all(R[:,1:] == R[:,:-1], axis=1)
V = R[~E]
print(V)


[[3 1 3]
 [4 4 4]
 [1 0 4]
 [0 4 1]
 [3 2 3]
 [4 0 0]
 [3 0 3]
 [4 3 4]
 [1 3 3]
 [3 1 3]]
[[3 1 3]
 [1 0 4]
 [0 4 1]
 [3 2 3]
 [4 0 0]
 [3 0 3]
 [4 3 4]
 [1 3 3]
 [3 1 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)¶


In [90]:
A = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(A[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)


In [91]:
Z = np.random.randint(0,10,(6,6))
u = np.unique(Z, axis=0)
u

array([[1, 9, 1, 6, 8, 2],
       [5, 7, 2, 1, 3, 5],
       [7, 8, 3, 6, 2, 6],
       [8, 8, 0, 4, 7, 5],
       [8, 9, 4, 9, 4, 3],
       [9, 5, 3, 9, 8, 5]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)¶


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?¶


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)¶


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)¶
